name: Build AppImage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare AppDir
      run: |
        mkdir -p AppDir/usr/bin
        cp -r app AppDir/usr/bin/
        cp ollama-tray.desktop AppDir/
        cp app/icon.png AppDir/icon.png
        echo '#!/bin/bash' > AppDir/AppRun
        echo 'exec python3 /usr/bin/app/ollama-tray.py' >> AppDir/AppRun
        chmod +x AppDir/AppRun

    - name: Download appimagetool
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Get Version
      id: get_version
      run: |
        VERSION=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build AppImage
      run: |
        ./appimagetool-x86_64.AppImage AppDir OllamaTray-${{ env.VERSION }}.AppImage

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: OllamaTray-${{ env.VERSION }}
        path: OllamaTray-${{ env.VERSION }}.AppImage
